version: '3'

services:

  backend:
    container_name: backend_rez
    # مسیری که باید دنبال داکر فایل بگرده
    build: .
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn core.wsgi --bind 0.0.0.0:8001"
    volumes:
      - .:/backend_rez
      - static_volume_rez:/backend_rez/static_file
      - media_volume_rez:/backend_rez/media
    ports:
      - 8001:8001

    environment:
      - DB_NAME=rezervation
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_PORT=3306
      - debug=True
      - ALLOWED_HOSTS=kodomja.ir,www.kodomja.ir
      - DJANGO_ENV=development

    networks:
      - shared_net
    restart: always

volumes:
  static_volume_rez:
  media_volume_rez:

networks:
  shared_net:
    external: true