# Generated by Django 4.2 on 2025-08-21 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rezervation', '0006_mosque_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='rezervation.mosque')),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occasions', to='website.category')),
            ],
        ),
        migrations.CreateModel(
            name='Night',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField()),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nights', to='website.occasion')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='media_files/')),
                ('title', models.CharField(max_length=255)),
                ('night', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='website.night')),
            ],
        ),
    ]
