# Generated by Django 4.2 on 2025-08-21 18:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_file_type_mediafile_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, null=True, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, null=True, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='night',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, null=True, populate_from='number'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, null=True, populate_from='name'),
        ),
    ]
