# Generated by Django 4.2 on 2025-08-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_category_slug_alter_mediafile_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(default='asghar', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='slug',
            field=models.CharField(default='asghar', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='night',
            name='slug',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
