# Generated by Django 4.2 on 2025-08-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_category_slug_alter_mediafile_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='image',
            field=models.ImageField(default='null', upload_to='media_night'),
        ),
        migrations.AddField(
            model_name='night',
            name='image',
            field=models.ImageField(default='null', upload_to='media_night'),
        ),
        migrations.AddField(
            model_name='occasion',
            name='image',
            field=models.ImageField(default='null', upload_to='media_night'),
        ),
    ]
