# Generated by Django 4.2 on 2025-08-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_mediafile_image_night_image_occasion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='ashghar', upload_to='', verbose_name='media_category_picture'),
            preserve_default=False,
        ),
    ]
