# Generated by Django 4.2 on 2025-08-26 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='style_media_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mediafile',
            name='type',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occasion',
            name='name',
            field=models.CharField(help_text='مناسبت + سال مثال : دهه اول ماه محرم 1404', max_length=200),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='style_media_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.style_media_file'),
        ),
    ]
