# Generated by Django 4.2 on 2025-08-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_style_media_file_mediafile_type_alter_occasion_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='night',
            name='slug',
            field=models.CharField(help_text='این فیلد به عنوان نام شب هم در کد استفاده شده است ', max_length=100),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.owner'),
        ),
    ]
