# Generated by Django 4.2 on 2025-08-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_owner_alter_night_slug_mediafile_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='type',
        ),
    ]
