# Generated by Django 4.2 on 2025-08-28 13:41

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_mediafile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
