# Generated by Django 4.2 on 2025-08-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_mediafile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='Selected',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
