# Generated by Django 4.2 on 2025-05-10 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='facility_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('facilities', models.ManyToManyField(blank=True, related_name='halls', to='rezervation.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('rigen', models.TextField()),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='mosques/logos/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('facilities', models.ManyToManyField(blank=True, related_name='mosques', to='rezervation.facility')),
            ],
        ),
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='halls/images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rezervation.hall')),
            ],
        ),
        migrations.AddField(
            model_name='hall',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='rezervation.mosque'),
        ),
    ]
