# Generated by Django 4.2 on 2025-06-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='قیمت پایه رزرو سالن به تومان', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
