# Generated by Django 4.2 on 2025-08-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('rezervation', '0002_hall_price_hall_video_file_alter_mosque_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
    ]
