# Generated by Django 4.2 on 2025-08-08 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('rezervation', '0003_mosque_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
