# Generated by Django 4.2 on 2025-08-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervation', '0004_alter_mosque_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosque',
            name='site',
        ),
    ]
