# Generated by Django 4.2 on 2025-08-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervation', '0006_mosque_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mosque',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
