# Generated by Django 4.2 on 2025-11-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0004_mosque_customer'),
        ('rezervation', '0007_mosque_meta_description_mosque_meta_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='rezervation.mosque')),
            ],
        ),
        migrations.AlterField(
            model_name='hall',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', related_query_name='hall', to='rezervation.mosque'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rezervation.availabletime')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervation.mosque')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_profile.mosque_customer')),
            ],
        ),
    ]
