# Generated by Django 4.2 on 2025-11-07 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezervation', '0008_availabletime_alter_hall_mosque_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='rezervation.mosque'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='price',
            field=models.IntegerField(help_text='قیمت پایه رزرو سالن به تومان', null=True),
        ),
    ]
