# Generated by Django 4.2 on 2025-11-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervation', '0009_alter_hall_mosque_alter_hall_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='type_hall',
            field=models.CharField(choices=[('salonejtemaat', 'سالن اجتماعات'), ('sahne_asli', 'صحن اصلی')], default='salonejtemaat', max_length=50),
        ),
    ]
