# Generated by Django 4.2 on 2025-05-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='my_user',
            managers=[
            ],
        ),
    ]
