# Generated by Django 4.2 on 2025-08-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezervation', '0007_mosque_meta_description_mosque_meta_title'),
        ('my_profile', '0002_alter_my_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque_operator',
            name='mosque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rezervation.mosque'),
            preserve_default=False,
        ),
    ]
