# Generated by Django 4.2 on 2025-11-07 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezervation', '0007_mosque_meta_description_mosque_meta_title'),
        ('my_profile', '0003_mosque_operator_mosque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=300)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervation.mosque')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
